
# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  download:
    cmd: stages/01_download.sh
    deps:
      - stages/01_download.sh
    outs:
      - download

  unzip: 
    cmd: stages/02_unzip.sh
    deps:
      - stages/02_unzip.sh
      - download
    outs:
      - raw

  build: 
    cmd: python stages/03_build.py
    deps:
      - stages/03_build.py
      - raw
    outs:
      - output.parquet  # Assuming this is the output of build.py
