stages:
  download:
    cmd: stages/01_download.sh
    deps:
      - stages/01_download.sh
    outs:
      - download

  unzip: 
    cmd: python stages/02_unzip_build.py
    deps:
      - stages/02_unzip_build.py
    outs:
      - brick/
